[Form] Checkbox
Groupe-Gaillard/purrfect-ui pull request #15
Opened 2024-06-19 14:21 UTC by Rcaradec

![image](https://github.com/Groupe-Gaillard/purrfect-ui/assets/72319136/f06b1e04-d8bf-48d2-be63-c23c17ae0efb)

2024-06-19 14:22 UTC, MatouTechnologies commented
This pull request has been deployed to Vercel.
<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://matou-technologies-purrfect-ui-storybook-15.vercel.app'>https://matou-technologies-purrfect-ui-storybook-15.vercel.app</a></td>
  </tr>
  <tr>
    <td><strong>🔍 Inspect:</strong></td>
    <td><a href='https://vercel.com/matou-technologies/purrfect-ui/AHjXxo4oC7KqvH75W6dP719XUFSf'>https://vercel.com/matou-technologies/purrfect-ui/AHjXxo4oC7KqvH75W6dP719XUFSf</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="deploy-preview-storybook"></hidden>

2024-06-20 09:17 UTC, Rcaradec commented on src/form/Checkbox/Checkbox.stories.tsx
> +      <Title style={{ width: "100%" }}>Checkbox</Title>
<img src="https://media0.giphy.com/media/w89ak63KNl0nJl80ig/giphy.gif"/>

2024-06-20 09:24 UTC, Balkeo requested changes

2024-06-20 09:24 UTC, Balkeo commented on src/form/Checkbox/Checkbox.stories.tsx
> +      <Title style={{ width: "100%" }}>Checkbox</Title>
Same here @Rcaradec

2024-06-20 09:24 UTC, Balkeo commented on src/form/Checkbox/Checkbox.stories.tsx
> +      <Title style={{ width: "100%" }}>Checkbox</Title>
Same here @Rcaradec

2024-06-20 12:16 UTC, MarcoPOtard commented on src/form/Checkbox/Checkbox.spec.tsx
> +        className=""
Est-ce nécessaire de passer value et className étant donné qu'ils sont vides

2024-06-20 12:16 UTC, MarcoPOtard commented on src/form/Checkbox/Checkbox.stories.tsx
> +    className: "",
Idem, le className est vide, je pense que ce n'est pas utile de le passer.

2024-06-20 12:16 UTC, MarcoPOtard commented on src/form/Checkbox/Checkbox.stories.tsx
> +    className: "",
même question

2024-06-20 12:16 UTC, MarcoPOtard commented on src/form/Checkbox/Checkbox.stories.tsx
> +    className: "",
la même ;)

2024-06-20 13:02 UTC, merged