[FORM]Add RadioGroup
Groupe-Gaillard/purrfect-ui pull request #18
Opened 2024-06-24 15:07 UTC by MarcoPOtard

2024-06-24 15:08 UTC, MatouTechnologies commented
This pull request has been deployed to Vercel.
<table>
  <tr>
    <td><strong>✅ Preview:</strong></td>
    <td><a href='https://matou-technologies-purrfect-ui-storybook-18.vercel.app'>https://matou-technologies-purrfect-ui-storybook-18.vercel.app</a></td>
  </tr>
  <tr>
    <td><strong>🔍 Inspect:</strong></td>
    <td><a href='https://vercel.com/matou-technologies/purrfect-ui/7KLCic2y25LLJGcMijVXv59tomFs'>https://vercel.com/matou-technologies/purrfect-ui/7KLCic2y25LLJGcMijVXv59tomFs</a></td>
  </tr>
</table>


<hidden purpose="for-rewritable-pr-comment-action-use" value="deploy-preview-storybook"></hidden>

2024-06-26 07:52 UTC, Balkeo requested changes

2024-06-26 07:52 UTC, Balkeo commented on src/form/RadioGroup/RadioGroup.tsx
> +      ))}
```suggestion
      {children}
```

2024-06-26 07:52 UTC, Balkeo commented on src/form/RadioGroup/RadioGroup.tsx
> +  radio: RadioProps[];
```suggestion
  children: React.ReactNode;
```

2024-06-26 08:01 UTC, MarcoPOtard commented on src/form/RadioGroup/RadioGroup.tsx
> +      ))}
Bien vu et plus logique, modifié

2024-06-26 08:01 UTC, MarcoPOtard commented on src/form/RadioGroup/RadioGroup.tsx
> +  radio: RadioProps[];
Bien vu et plus logique, modifié

2024-06-26 14:33 UTC, Balkeo commented on src/form/Radio/Radio.stories.tsx
> +import Radio from "./Radio";
Please use absolute Imports

2024-06-26 14:33 UTC, Balkeo commented on src/form/RadioGroup/RadioGroup.spec.tsx
> +import RadioGroup from "./RadioGroup";
Please use absolute Imports

2024-06-26 14:33 UTC, Balkeo commented on src/form/RadioGroup/RadioGroup.stories.tsx
> +import { heading1, sizing } from "../../guidelines/theme/index";
Please use absolute Imports

2024-06-26 14:34 UTC, Balkeo commented on src/form/RadioGroup/RadioGroup.tsx
> +import { typographies } from "../../guidelines/theme/typographies";
Please use absolute Imports

2024-06-26 14:34 UTC, Balkeo commented on src/form/Radio/Radio.tsx
> +import { body1, sizing, theme } from "../../guidelines/theme";
Please use absolute Imports

2024-06-26 14:34 UTC, Balkeo commented on src/form/Radio/Radio.spec.tsx
> +import RadioGroup from "../RadioGroup/RadioGroup";
Please use absolute Imports

2024-06-26 15:01 UTC, merged