[Purrfect-UI] Theme Border Radius
Groupe-Gaillard/purrfect-ui pull request #6
Opened 2024-06-14 15:37 UTC by Rcaradec

![image](https://github.com/Groupe-Gaillard/purrfect-ui/assets/72319136/397c2a73-7c24-4ee9-86d6-3adbc5333fda)

2024-06-17 06:52 UTC, MarcoPOtard reviewed
Merci pour la correction du typage sur la fonction de contraste.
Je pense qu'on va rapidement devoir sortir cette fonction de contraste pour l'utiliser partout, dans les stories et dans le code des composant. Il faut qu'on en discute.

2024-06-17 06:52 UTC, MarcoPOtard commented on src/guidelines/theme/borders.stories.tsx
> +  size?: "small" | "big";
Quelle est l'utilité de size ?
Ce square n'est utile que pour la story de présentation des border, comme tu n'utilises pas size, je pense qu'on peut le supprimer ?

2024-06-17 15:43 UTC, MarcoPOtard commented on src/guidelines/theme/borders.stories.tsx
> +import { theme } from "./index";
Tu peux regrouper les appels des lignes 4 et 5

2024-06-17 15:43 UTC, MarcoPOtard commented on src/guidelines/theme/index.ts
> +export type { HexColor } from "../..//utils/utils";
il y a un double / dans l'url

2024-06-17 15:43 UTC, MarcoPOtard commented on src/guidelines/theme/index.ts
> +export { getContrastYIQ, spacing } from "../../utils/utils";
Tu peux regrouper les lignes 1 et 2

2024-06-17 16:06 UTC, Rcaradec commented on src/guidelines/theme/borders.stories.tsx
> +  size?: "small" | "big";
supprimé

2024-06-18 06:21 UTC, Rcaradec commented on src/guidelines/theme/index.ts
> +export { getContrastYIQ, spacing } from "../../utils/utils";
dans ce cas, non, car HexColor est un type.

2024-06-18 06:51 UTC, MarcoPOtard commented on src/guidelines/theme/index.ts
> +export { getContrastYIQ, spacing } from "../../utils/utils";
en effet :)

2024-06-18 09:07 UTC, Balkeo requested changes

2024-06-18 09:07 UTC, Balkeo commented on src/guidelines/theme/typographies.ts
> +  margin: ${spacing(24)} 0 ${spacing(16)};
```suggestion
```

2024-06-18 09:07 UTC, Balkeo commented on src/guidelines/theme/typographies.ts
> +  margin: ${spacing(24)} 0 ${spacing(16)};
```suggestion
```

2024-06-18 09:07 UTC, Balkeo commented on src/guidelines/theme/typographies.ts
> +  margin: ${spacing(24)} 0 ${spacing(16)};
```suggestion
```

2024-06-18 09:07 UTC, Balkeo commented on src/guidelines/theme/typographies.ts
> +  margin: ${spacing(16)} 0 ${spacing(12)};
```suggestion
```

2024-06-18 09:07 UTC, Balkeo commented on src/guidelines/theme/typographies.ts
> +  margin: ${spacing(12)} 0 ${spacing(8)};
```suggestion
```

2024-06-18 09:07 UTC, Balkeo commented on src/guidelines/theme/typographies.ts
> +  margin: ${spacing(12)} 0 ${spacing(8)};
```suggestion
```

2024-06-18 09:57 UTC, merged